---

- hosts: all
  become: true
  tasks: 

  - name: install apache2 package and php support for apache package
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"] or ansible_facts ["distribution_release"] == "orel"
