---

- hosts: all
  become: true
  tasks: 
  
  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu", "Astra Linux (Orel)"]

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"] or ansible_facts ["distribution_release"] == "arel"

  - name: add php support for apache
    apt: 
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"] or ansible_distribution_release == "orel"
